# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0002_auto_20160628_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='login_reg.Gender'),
        ),
    ]
