# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0002_auto_20160628_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opta', to='dating_app.Option')),
                ('option_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optb', to='dating_app.Option')),
                ('option_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optc', to='dating_app.Option')),
                ('option_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optd', to='dating_app.Option')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.IntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating_app.Option')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_reg.User')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dating_app.Question')),
            ],
        ),
    ]
